### ISSUE TITLE
Couenne fails to build with gcc 6.2.1

### ISSUE THREAD

**Issue by mlubin** [coin-or/Couenne#1]
See discussion and proposed fix by @tkelman at https://github.com/JuliaOpt/CoinOptServices.jl/issues/27#issuecomment-290960312.

**Comment by tkelman** [comment]
Not positive if that's a totally general fix, may want something more specific that checks if strtod has been redefined to strtod_ASL and only then undefines it

**Comment by merraksh** [comment]
I went for the more draconian #undef of strtod, since it can be #defined as
some other struct's Strtod. Sorry for the really slow response. Committed
to Couenne stable/0.5 and trunk.
