### ISSUE TITLE
Error Using Couenne Through Julia

### ISSUE THREAD

**Issue by svigerske** [coin-or/Couenne#40]
Issue created by migration from Trac.

Original creator: muriloasouza

Original creation time: 2018-07-24 11:55:00

Assignee: @merraksh

Version: 

Hello, i'm having a problem when i try to solve a MINLP in Atom (Julia Programing Language).

This is the problem i'm trying to solve:

min   100*(x5 - (0.5 + x4)^2^)^2^ + (1 - x4)^2

s.t.  x4*x3 + x5*x1 <= 20

       5*x1 - 2*x5 + 3*x3 <= 17

       x4, x5 binary

       0 <= x1 <= 3

       0 <= x2 <= 5

       0 <= x3 <= 10
 

When i run my code in Atom, using Couenne as solver, I get the following solution:

objective function value = 0.24937733210128057

x1 = 1

x2 = 2.5

x3 = 2

x4 = 0.50124

x5 = 1

So, x4 in the solution is not binary. Is this a bug in Couenne?

Thanks in advance!

**Comment by svigerske** [comment]
Attachment [JuMP_PBin2.jl](https://www.coin-or.org/issue-attachments/Couenne/ticket40/JuMP_PBin2.jl) by muriloasouza created at 2018-07-24 11:57:27

Code_in_the_Julia_Language.

**Comment by svigerske** [comment]
Comment by @merraksh created at 2018-07-26 08:01:15

Hi,

is there any way in Julia/JuMP to write a MINLP to the .nl format read by Couenne, and if so, can you attach the .nl file? That would help understand what the problem is, as I don't have Julia installed.

**Comment by svigerske** [comment]
Comment by muriloasouza created at 2018-07-30 13:26:17

Replying to [comment:1 pbelotti]:
> Hi,
> 
> is there any way in Julia/JuMP to write a MINLP to the .nl format read by Couenne, and if so, can you attach the .nl file? That would help understand what the problem is, as I don't have Julia installed.

Hello,

I really don't know. I'm fairly new to Julia. But here's the code i wrote, if that helps you in anyway:


```
using JuMP, CouenneNL

m = Model(solver=CouenneNLSolver())

X_U = [3;5;10]

`@`variable(m, 0 <= X[i=1:3] <= X_U[i])

`@`variable(m, x[i=4:5], Bin)

`@`NLobjective(m, Min, 100*(x[5] - (0.5 + x[4])^2)^2 + (1 - x[4])^2)

`@`NLconstraint(m, x[4]*X[3]+x[5]*X[1] <= 20)

`@`constraint(m, 5*X[1]-2*x[5]+3*X[3] <= 17)

print(m)

status = solve(m)

println("Objective value: ", getobjectivevalue(m))
println("x = ", getvalue(x))
println("X = ", getvalue(X))
```

Something to be noted, is that Couenne is aware of the number of integer variables (5 Variables, 2 integers). But that restriction is not being enforced.

**Comment by odow** [comment]
This can be closed. It is a bug in the AmplNLWriter with variable ordering: https://github.com/JuliaOpt/AmplNLWriter.jl/pull/101

**Comment by tkralphs** [comment]
Thanks!
