### ISSUE TITLE
Problem during compilation of Couenne 0.5.7

### ISSUE THREAD

**Issue by ycollet** [coin-or/Couenne#45]
During compilation, an error message shows up:
```
Couenne-0.5.7/Couenne/src/problem/CouenneProblemConstructors.cpp:97:17: erreur: #if with no expression
   97 | #if COIN_HAS_ASL
```

**Comment by merraksh** [comment]
That #if should be replaced by a #ifdef. I'll make the change in trunk and 0.5 but you should make that change in 0.5.7 as that is a release.

**Comment by tkralphs** [comment]
@merraksh I didn't see this fix added, just checking that you just haven't gotten to
it yet.

**Comment by merraksh** [comment]
Correct, I'll get to it soon.
