### ISSUE TITLE
couenne: error while loading shared libraries: libcoinscip.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yifanguan** [coin-or/Couenne#46]
My system: Linux Ubuntu 16.04
I followed the installation instruction listed in Github README.
I downloaded all required third-party codes as well.
All other commands installed along with couenne work fine (e.g. bonmin, cbc, etc).

I got the following error when I try to run couenne command:
couenne: error while loading shared libraries: libcoinscip.so.0: cannot open shared object file: No such file or directory

Please help! Thanks!

**Comment by merraksh** [comment]
Hi,

you may want to try to re-configure with the option --without-scip.

Regards,

Pietro

**Comment by tkralphs** [comment]
That is quite strange. Can you post the exact sequence of commands? You
should not get a dependence on SCIP unless you downloaded SCIP manually
yourself. I don't see much reason to do that with Couenne.

The easiest way to get all the dependencies and to build Couenne these days
is to use coinbrew (https://coin-or.github.io/coinbrew). When I get a
little time, I'll change the README to reflect that.

**Comment by yifanguan** [comment]
@merraksh Thank you for answering! Is SCIP a mandatory part of Couenne? My program needs precise solutions, and I do not care about runtime speed.

**Comment by yifanguan** [comment]
@tkralphs I followed the instruction in ThirdParty/SCIP/INSTALL.SCIP, which asks me to download files from the SCIP website and put the extracted folder inside ThirdParty/SCIP as ThirdParty/SCIP/scip.

The exact sequence of commands I used:
cd Couenne
cd ThirdParty      # Read INSTALL.* file in each subdirectory and get third party software
cd ..
mkdir build
cd build
../configure -C --prefix=/usr/local
make
make install

It seems coinbrew is much easy to use to install Couenne. Thank you!

**Comment by merraksh** [comment]
Hi,

no, SCIP is not mandatory unless you want to use the Feasibility Pump heuristic, which is computationally heavy and therefore not on by default. If you care about precise solution you don't need to download SCIP.

Regards,

Pietro

**Comment by yifanguan** [comment]
@tkralphs coinbrew works like a charm.
In case anyone wants to know how to use it,
these are the command I execute in order:
```
wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
chmod u+x coinbrew
./coinbrew fetch Couenne@0.5.8
./coinbrew build Couenne --test --enable-debug --prefix=/usr/local
```
Thank you to @tkralphs and @merraksh for quick responses.
I'm going to close this issue.
If I have other questions, I will open a new issue.
