### ISSUE TITLE
Couenne not building 

### ISSUE THREAD

**Issue by 10000turtles** [coin-or/Couenne#71]
Hey there!

I am trying to build Couenne on my machine and I am encountering some issues. I am running the command,
`sudo ./coinbrew build Couenne --prefix=/usr/local --tests none --no-third-party `
on wsl Ubuntu version. The reason I am using `--tests none` is because Coin Utils unit test fails if you do that. The reason I am using `--no-third-party` is because Mumps will fail if you try to build it. The error I get when I build Couenne is in the file attached,

[Couenne Error.txt](https://github.com/coin-or/Couenne/files/10956789/Couenne.Error.txt)

 Thanks so much! 

Sincerely,

Justin Mucelli :D

**Comment by svigerske** [comment]
Should have been fixed on master (1cc279978), but no one has been doing releases here. You could apply that patch on your clone of Couenne or try to tell `coinbrew` to build master.

**Comment by 10000turtles** [comment]
Hey there again!

I switched Couenne to the master branch and this time encountered a different error that looks like this,

[Couenne Error 2.txt](https://github.com/coin-or/Couenne/files/10961963/Couenne.Error.2.txt)

Just to clarify, I went into the Couenne folder in coinbrew and ran the command `git switch master` to get to the master branch. Then I tried building using the same command as before. Thanks so much!

-Justin :D

**Comment by tkralphs** [comment]
The Couenne `master` branch is unlikely to be compatible with the versions you have checked out already. You should `coinbrew fetch Couenne@master` to switch all projects to a compatible version.

**Comment by tkralphs** [comment]
By the way, this can be done "in place". `coinbrew` checks whether each dependent project is already checked out and automatically does a `git switch` to checkout the branch corresponding to whatever version is requested if the project is already present.

**Comment by 10000turtles** [comment]
I think for some reason I am cursed because I keep running into errors haha. When I do `./coinbrew fetch Couenne@master` it will try to get ThirdParty/HSL master which made the error: `error: pathspec 'master' did not match any file(s) known to git`. I also tried fetching with the `--no-third-party` tag and coinbrew still tried to get HSL. I even tried manually updating all of the repos inside coinbrew to master by running `git switch master` but I still encountered the same error as before. Sorry for all the troubles. And thanks a bunch again :D

-Justin :D

**Comment by svigerske** [comment]
You can try again.
There may be new issues.

**Comment by 10000turtles** [comment]
Hey there. I am still encountering the same issue with `COUENNE_LAPACK_FUNC` even after switching the versions. I am wondering if maybe there is an issue with my machine? Maybe with the distribution of linux I am using for wsl? Are you two getting these issues trying to build? Let me know if I should switch something up. Also, my current commands for encountering this error from a "blank slate" are as follows,

`wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew`
`sudo ./coinbrew fetch Couenne@master`
`sudo ./coinbrew build Couenne --skip-dependencies --tests none`

Thanks so much again :D

-Justin

**Comment by 10000turtles** [comment]
Oh also, I have tried without `--skip-dependaencies` and it fails on Mumps because there is no Lapack, and I have tried with `--no-third-party` and gotten the same error. Thanks!

**Comment by svigerske** [comment]
hmm, could be better now (79872a7512).

>  Are you two getting these issues trying to build?

No, but we have Lapack. And we seldom try to build Couenne.

You will need Lapack to get Ipopt working. And you'll need at least one linear solver for Ipopt. Mumps is often the easiest choice. Couenne will probably not run without Ipopt.

**Comment by 10000turtles** [comment]
Okay, tried the same procedure again and encountered a new error:

[Couenne Error 3.txt](https://github.com/coin-or/Couenne/files/10971237/Couenne.Error.3.txt)

On a separate note, I noticed that Lapack isn't one of the repositories in coin-or. Is there a good way for me to install it so that it can be used for Ipopt/Couenne? 

Also another separate note, I am trying to use Couenne to do some non-convex non-linear optimization. I was told by my professor at school that Couenne with pyomo was the best way of doing that (pyomo with couenne works like this I think `pyo.SolverFactory('couenne') #and also add other code here for modeling/solving`). Is there something else in the coin-or suite that will work? (I really would like to get Couenne to work though because I am stubborn :D)

Thanks so much again!

Sincerely, 
Justin :D

**Comment by svigerske** [comment]
Don't know how to fix the error you get now. `BONMINLIB_EXPORT` should be defined in `BonminConfig.h`, which is included by `BonCbc.hpp`, which is included by `CouenneBab.cpp` before the lines that given an error.

Blas/Lapack is usually available from your distribution's (probably Ubuntu in your case) package managers.

In COIN-OR, I think Couenne is the only general global MINLP solver. If you have quadratic only, Minotaur or SHOT (with Gurobi) could be a good choice. Then there are other global MINLP solvers outside COIN-OR.

**Comment by tkralphs** [comment]
It's really not possible to tell what's going on from the information you've provided. You mentioned that you tried the `--skip-dependencies` option, but that would imply you have some dependencies installed already by some other means (such as through your package manager). If that is the case, you may be mixing incompatible versions. If you start from scratch with coinbrew in a  newly created directory, showing every command and _**all**_ the output, we can perhaps diagnose the issue. After that, we may need to have you do the build with higher verbosity or to get one of the config.log files that are produced.

**Comment by 10000turtles** [comment]
Hey there again. So, starting from scratch I ran the following commands,
`wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew`
`sudo ./coinbrew fetch Couenne@master`

and obtained the following output:

[wget and fetch Couenne Master.txt](https://github.com/coin-or/Couenne/files/10983416/wget.and.fetch.Couenne.Master.txt)

Next, I tried building normally with the following command,
`sudo ./coinbrew build Couenne --tests none -v 4`

and obtained the following output,

[build with verbosity 4.txt](https://github.com/coin-or/Couenne/files/10983421/build.with.verbosity.4.txt)

Then, I tried building ONLY couenne with the skip dependencies flag with the command,
`sudo ./coinbrew build Couenne --skip-dependencies --tests none -v 4`
and obtained the following output,

[build with verbosity 4 skip dependencies.txt](https://github.com/coin-or/Couenne/files/10983443/build.with.verbosity.4.skip.dependencies.txt)

I also realized from the first compilation that I needed lapack so I used the command 
`sudo apt-get install libblas-dev liblapack-dev`

to get lapack and then re-tried building with
`sudo ./coinbrew build Couenne --tests none -v 4`

and obtained the same error as before,
[build with verbosity 4 after installing lapack.txt](https://github.com/coin-or/Couenne/files/10983453/build.with.verbosity.4.after.installing.lapack.txt)

As well, I am using wsl with Ubuntu.

Hopefully this is enough info to diagnose the errors, please let me know if you need any more info :D.

Thanks a bunch!

Justin :D

**Comment by svigerske** [comment]
There are probably are some leftovers from an old Bonmin installation in `/usr/local/include/coin`, so your Couenne build includes the wrong header files.

From the last log, I cannot really say why it adds `-I/usr/local/include/coin` to the compiler flags. And I didn't check the other logs.

**Comment by tkralphs** [comment]
Yes, you need to do a complete uninstall before re-building. I guess that since each package gets installed after it is built, the header installation path, which is `/usr/local/include/coin`, is added to the header search path in order to allow the headers for the previously installed dependencies to be found. But since there are old headers from a previous build of Couenne sitting in there, they also get picked up. It should be fine to just delete the `/usr/local/include/coin` directory and then run the build command again. I guess that will fix your issue.

In general, the best way to avoid this kind of thing is to _build and install_ in a separate temporary directory until you get everything working. So you would do
```
sudo ./coinbrew build Couenne --tests none -v 4 -b ~/tmp_build_install -p
```
The `-b` is to specify the build directory and the `-p` is for the install directory, which defaults to the build directory if you don't specify anything. The advantage of this is that deleting ~/tmp_build_install will completely uninstall everything and get you back to a clean slate easily. 

Once the build succeeds, then re-build again without specifying a local build directory. Or it's also actually fine to just leave in a local directory and just add to your `PATH` and `LD_LIBRARY_PATH` variables.

**Comment by 10000turtles** [comment]
Hello again,

That worked!!! I went in, deleted the `/usr/local/include/coin` folder and then re-built it and it worked. I am very new/inexperienced at building so I will definitely be using that trick in the future. Thank you two so much for your help!!! 

Btw, just a heads up to you two and anyone else who tries to build this in the future, if you don't use `--tests none` in the build, it will take approximately an eternity to run. I had to stop it after around an hour because it was doing so many unit tests.  

Thank you so much again!!!

Sincerely,
Justin Mucelli :D

**Comment by defencedog** [comment]
I am still having issue referenced in https://github.com/coin-or/Couenne/issues/71#issuecomment-1468486957

```

git clone https://github.com/coin-or/Couenne.git
FC=gfortran-11 CC=gcc-11 CXX=g++-11 CXXFLAGS=-Wno-register ./configure --prefix=$PREFIX --with-bonmin --with-asl CPPFLAGS="-I/data/data/com.termux/files/usr/local/include/coin/ -I/data/data/com.termux/files/usr/local/include/coin/ThirdParty -I/data/data/com.termux/files/usr/local/include/coin-or/ -I/data/data/com.termux/files/usr/local/include/" --with-lapack="-L/data/data/com.termux/files/usr/include/openblas/ -lopenblas" --without-cplex --without-osicpx --without-osigrb  --without-osimsk --without-nauty && make -j4

configure: WARNING: unrecognized options: --with-asl       checking build system type... armv8l-unknown-linux-gnueabi checking host system type... armv8l-unknown-linux-gnueabi
checking for a BSD-compatible install... /data/data/com.termux/files/usr/bin/install -c
checking whether build environment is sane... yes          checking for a race-free mkdir -p... /data/data/com.termux/files/usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... yes (GNU style)
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc-11 accepts -g... yes
checking for gcc-11 option to enable C11 features... none needed
checking whether gcc-11 understands -c and -o together... yes                                                         checking dependency style of gcc-11... gcc3
checking whether the compiler supports GNU C++... yes      checking whether g++-11 accepts -g... yes
checking for g++-11 option to enable C++11 features... none needed
checking dependency style of g++-11... gcc3                checking whether g++-11 understands -c and -o together... yes                                                         checking how to print strings... printf
checking for a sed that does not truncate output... /data/data/com.termux/files/usr/bin/sed
checking for grep that handles long lines and -e... /data/data/com.termux/files/usr/bin/grep
checking for egrep... /data/data/com.termux/files/usr/bin/grep -E
checking for fgrep... /data/data/com.termux/files/usr/bin/grep -F
checking for ld used by gcc-11... /data/data/com.termux/files/usr/bin/ld
checking if the linker (/data/data/com.termux/files/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /data/data/com.termux/files/usr/bin/nm -B
checking the name lister (/data/data/com.termux/files/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 32768
checking how to convert armv8l-unknown-linux-gnueabi file names to armv8l-unknown-linux-gnueabi format... func_convert_file_noop
checking how to convert armv8l-unknown-linux-gnueabi file names to toolchain format... func_convert_file_noop
checking for /data/data/com.termux/files/usr/bin/ld option to reload object files... -r                               checking for file... file
checking for objdump... objdump                            checking how to recognize dependent libraries... pass_all
checking for dlltool... no                                 checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /data/data/com.termux/files/usr/bin/nm -B output from gcc-11 object... ok
checking for sysroot... no
checking for a working dd... /data/data/com.termux/files/usr/bin/dd
checking how to truncate binary pipes... /data/data/com.termux/files/usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking the archiver (ar) interface... ar
checking for objdir... .libs
checking if gcc-11 supports -fno-rtti -fno-exceptions... no
checking for gcc-11 option to produce PIC... -fPIC -DPIC   checking if gcc-11 PIC flag -fPIC -DPIC works... yes       checking if gcc-11 static flag -static works... no
checking if gcc-11 supports -c -o file.o... yes
checking if gcc-11 supports -c -o file.o... (cached) yes   checking whether the gcc-11 linker (/data/data/com.termux/files/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes       checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++-11 -E      checking for ld used by g++-11... /data/data/com.termux/files/usr/bin/ld                                              checking if the linker (/data/data/com.termux/files/usr/bin/ld) is GNU ld... yes                                      checking whether the g++-11 linker (/data/data/com.termux/files/usr/bin/ld) supports shared libraries... yes          checking for g++-11 option to produce PIC... -fPIC -DPIC   checking if g++-11 PIC flag -fPIC -DPIC works... yes       checking if g++-11 static flag -static works... no
checking if g++-11 supports -c -o file.o... yes            checking if g++-11 supports -c -o file.o... (cached) yes
checking whether the g++-11 linker (/data/data/com.termux/files/usr/bin/ld) supports shared libraries... yes          checking dynamic linker characteristics... (cached) GNU/Linux ld.so                                                   checking how to hardcode library paths into programs... immediate                                                     checking for pkgconf... no                                 checking for pkg-config... pkg-config
checking pkg-config is at least version 0.16.0... yes: 0.29.2
configure: pkg-config path is "/data/data/com.termux/files/usr/lib/pkgconfig:"                                        checking for package Bonmin... yes                         checking for package BonminAmpl... yes                     checking for package OsiCpx... skipping                    checking for package OsiGrb... skipping                    checking for package OsiMsk... skipping                    checking for package OsiSpx... no
checking for package OsiXpr... no                          checking for package Nauty... skipping
checking for library SCIP with link check... no (bare link)configure: Compiler flags were "". Use --with-scip-cflags to overwrite. Check config.log for details of failed compile attempt.                                                  configure: Linker flags are "-lscipsolver". Use --with-scip-lflags to overwrite. Check config.log for details of failed link attempt.                                            checking for library Cplex with link check... skipping (command line)                                                 checking for LAPACK... 0
9
yes: user-specified (-L/data/data/com.termux/files/usr/include/openblas/ -lopenblas)
checking for cstdint... yes
configure: configuring doxygen documentation options       checking for doxygen... no                                 checking for latex... no                                   checking for dot... NO                                     checking that generated files are newer than configure... done                                                        configure: creating ./config.status
config.status: creating Makefile
config.status: creating test/Makefile                      config.status: creating src/main/Makefile                  config.status: creating src/bound_tightening/Makefile      config.status: creating src/bound_tightening/twoImpliedBT/Makefile                                                    config.status: creating src/branch/Makefile                config.status: creating src/convex/Makefile
config.status: creating src/interfaces/Makefile            config.status: creating src/heuristics/Makefile            config.status: creating src/disjunctive/Makefile           config.status: creating src/cut/crossconv/Makefile         config.status: creating src/cut/sdpcuts/Makefile           config.status: creating src/expression/Makefile            config.status: creating src/problem/Makefile
config.status: creating src/standardize/Makefile           config.status: creating src/util/Makefile                  config.status: creating src/Makefile                       config.status: creating test/grandTest.sh                  config.status: creating couenne.pc                         config.status: creating doxydoc/doxygen.conf               config.status: creating src/config.h
config.status: creating src/config_couenne.h               config.status: executing depfiles commands                 config.status: executing libtool commands                  configure: WARNING: unrecognized options: --with-asl       configure: Configuration of Couenne successful
```

![Screenshot_20240215_195234_Termux](https://github.com/coin-or/Couenne/assets/831749/e1a1e3d8-1bdd-4c9c-a362-541fe5817a96)

**Comment by tkralphs** [comment]
I would suggest to read all the advice provided above and make sure you understand it fully. It is highly likely that the failure is happening for the same or related reasons, but there is no way to tell from the information provided exactly what is happening. You will save yourself a lot of trouble if you just use `coinbrew` to build, as recommended above. Feel free to ask if you need anything clarified, but please do take the time to understand the conversation above first.

**Comment by svigerske** [comment]
`CPPFLAGS="-I/data/data/com.termux/files/usr/local/include/coin/ -I/data/data/com.termux/files/usr/local/include/coin/ThirdParty -I/data/data/com.termux/files/usr/local/include/coin-or/` looks like you mix old versions of some dependencies with new ones. `BONMINLIB_EXPORT` is only defined in the master branch of Bonmin. Couenne's master branch assumes Bonmin's master branch (and default branches for all other depenencies).

I agree with Ted that `coinbrew` would sort out getting and building the right versions of dependencies for you.
